version: '3.8'

services:

  #API
  gestao-escolar-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: gestao-escolar-api:1.0
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: ${FLASK_ENV}
      FLASK_APP: ${FLASK_APP}
    volumes:
      - .:/app
    depends_on:
      - db

  #Banco de Dados
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
